config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/auth', to: 'auth#index'
  root "categorys#index"
  resources :categorys, only: [:show, :index, :new, :create] do
    resources :transactions, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_transactions, dependent: :destroy
  has_many :expenses, through: :category_transactions, dependent: :destroy, class_name: 'Transaction'
  validates :name, :icon, :user_id, presence: true
end

app/models/category_transaction.rb
class CategoryTransaction < ApplicationRecord
  belongs_to :expense, class_name: 'Transaction'
  belongs_to :category
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :categorys, through: :category_transactions
  has_many :category_transactions
  validates :name, :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :transactions
  has_many :categorys
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def after_sign_out_path_for(_resource_or_scope)
    auth_path
  end

  def authenticate_user!
    return if user_signed_in?

    current_uri = request.env['PATH_INFO']
    unless [auth_path, '/users/sign_in', '/users/sign_up', '/users/password/new',
            user_password_path, user_registration_path].include?(current_uri)
      redirect_to auth_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation, :name)
    end
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def index
    return unless user_signed_in?

    redirect_to root_path
  end
end

app/controllers/categorys_controller.rb
class CategorysController < ApplicationController
  def index
    @title = 'Categories'
    @rigth_el = 'menu'
    @left_el = 'search'
    @categories = Category.includes(:expenses).where(user_id: current_user.id)
  end

  def show
    @category = Category.includes(:expenses).find(params[:id])
    @transactions = @category.expenses
  end

  def new
    @category = Category.new
  end

  def create
    user = current_user
    @category = user.categorys.new(params.require(:category).permit(:name, :icon))
    if @category.save
      redirect_to categorys_path, notice: 'Category created successfully'
    else
      redirect_to categorys_path, alert: 'An error occured when creating the category'
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @transaction = Transaction.new
    @category = Category.find(params[:category_id])
  end

  def create
    user = current_user
    @transaction = Transaction.new(params.require(:transaction).permit(:name, :amount))
    @transaction.author = user
    @category_transaction = CategoryTransaction.new(expense: @transaction, category_id: params[:category_id])

    if @transaction.save && @category_transaction.save
      params[:categorys]&.each do |category_id|
        CategoryTransaction.create(expense: @transaction, category_id:)
      end
      redirect_to category_path(params[:category_id]), notice: 'Transaction created successfully'
    else
      redirect_to category_path(params[:category_id]), alert: 'An error occured when creating the transaction'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/category/index.html.erb
<%=render "shared/navbar", right_el: "menu", left_el: "search", title: "CATEGORIES"%>
<%# <div class="category-list-container"> %>
    <ul class="category-list d-flex flex-column align-items-center m-auto  p-3">
        <%for a in 0..30 do%>
            <%= render "category/shared/category"%>
        <%end%>
    </ul>
<%# </div> %>

app/views/category/shared/_category.html.erb
<div class="category-container bg-primary d-flex justify-content-between p-2">
    <div class="img-container">
        <img src="https://cdn-icons-png.flaticon.com/512/781/781760.png" class="img-thumbnail w-100 h-100" alt="icon">
    </div>
    <div class="category-details">
        <h3>
            Shopping and utitlities
        </h3>

        <em>14 April 2014</em>
    </div>

    <div>
        <h4>Total: <br/>
            $100
        </h4>

    </div>
</div>

app/views/categorys/index.html.erb
<%=render "shared/navbar", right_el: "menu", left_el: "search", title: "CATEGORIES"%>
    <ul class="category-list d-flex flex-column align-items-center m-auto  p-3">
        <%@categories.each do |category|%>
            <%=link_to category_path(category), class:"w-100 link-to-item" do%>
                <%= render "categorys/shared/category", category: category%>
            <%end%>
        <%end%>
        <%if @categories.empty?%>
            <p>You don't have any registered category!</p>
         <%end%>
    </ul>
<%=render "shared/add_new", type: "category"%>

app/views/categorys/new.html.erb
<%=render "shared/navbar", right_el: "back", left_el: "none", title: "New Category"%>

<%= form_with model: @category, url: categorys_path, method: :post, local: true, scope: :category, class:"p-3 category-form" do |f|%>
    <div class="mb-3">
        <%= f.label :name, "Name", class:"form-label" %><br>
        <%= f.text_field :name,  :required => true, class:"form-control", placeholder: "Enter the name of the category" %>
    </div>
    <div class="mb-3">
        <%= f.label :icon, "Icon", class:"form-label" %><br>
        <%= f.text_field :icon,  :required => true, class:"form-control icon-input" %>
        <div id="icon-error" class="form-text d-none"></div>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
<%end%>

<script>
    const iconError = document.querySelector("#icon-error");
const iconInput = document.querySelector(".icon-input");
const categoryForm = document.querySelector(".category-form");

const showMessage = (succes) => {
  if (succes) {
    iconError.classList.remove("text-danger");
    iconError.classList.add("text-success");
    iconError.classList.remove("d-none");
    iconError.textContent = "Your url is a valid image url";
  } else {
    iconError.classList.remove("text-success");
    iconError.classList.add("text-danger");
    iconError.classList.remove("d-none");
    iconError.textContent = "Please provide an image link";
  }

  const t = setTimeout(() => {
    iconError.classList.add("d-none");
    clearTimeout(t);
  }, 5000);
};

function isImgUrl(url) {
  const img = new Image();
  img.src = url;
  return new Promise((resolve) => {
    img.onload = () => resolve(true);
    img.onerror = () => resolve(false);
  });
}

let urlTest = false;

  console.log("First");
  iconInput.addEventListener("change", async (e) => {
    urlTest = await isImgUrl(e.target.value);
    showMessage(urlTest);
  });

  console.log("seond");
  console.log(window.location);
  //prevent the form from being submited if the link is not an image lintk
  categoryForm.addEventListener("submit", async (e) => {
    if (!urlTest) e.preventDefault();
    console.log(urlTest);
  });

</script>

app/views/categorys/shared/_category.html.erb
<div class="category-container bg-light d-flex justify-content-between align-items-around p-2">
    <div class="img-container">
        <img src= <%=category.icon%> class="img-thumbnail w-100 h-100" alt="icon">
    </div>
    <div class="category-details">
        <h3>
            <%=category.name%>
        </h3>

        <em>14 April 2014</em>
    </div>

    <div class="category-total">
        <h4>
            $<%=category.expenses.sum(:amount)%>
        </h4>

    </div>
</div>

app/views/categorys/show.html.erb
<%=render "shared/navbar", right_el: "back", left_el: "none", title: "DETAILS"%>
<div class="bg-light m-3 p-2">
    <div class="category-head d-flex align-items-center">
        <div class="img-container">
            <img src=<%=@category.icon%> class="img-thumbnail w-100 h-100" alt="icon">
        </div>
        <h3 class="ms-2"><%=@category.name%></h3>
    </div>

    <h3 class="transactions-list-title my-3">Transactions:</h3>

    <ul class="transactions-list d-flex flex-column ps-0">
       <%@transactions.each do |transaction|%>
            <%= render "transactions/shared/transaction", transaction: transaction%>
        <%end%>
    </ul>
    <%if @transactions.empty?%>
        <p>This Category is empty!</p>
    <%end%>
    <div class="d-flex justify-content-between total-amount">
        <h3>TOTAL AMOUNT:</h3>
        <h3>$<%=@transactions.sum(:amount)%></h3>
    </div>
</div>
<%=render "shared/add_new", type: "transaction"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="alert-container">
        <% flash.each do |type, msg| %>
          <%if type == "notice"%>
            <div class="w-100 alert alert-success d-flex align-items-center alert-dismissible fade show alert-component" role="alert">
              <i class="bi bi-check-circle-fill me-2"></i>
              <div>
                <%=msg%>
              </div>
              <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
            </div>
          <%else%>
            <div class="w-100 alert alert-warning d-flex align-items-center alert-dismissible fade show alert-component" role="alert">
              <i class="bi bi-exclamation-triangle-fill me-2"></i>
              <div>
                <%=msg%>
              </div>
              <button type="button" class="btn-close" aria-label="Close" data-bs-dismiss="alert"></button>
            </div>
          <%end%>
      <%end%>
    </div>

    <div class="main-container m-auto bg-body-secondary">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_add_new.html.erb
<div class="sticky-bottom p-2 add_new">
    <%if type == "category"%>
        <%=link_to new_category_path do%>
            <button type="button" class="btn btn-outline-light w-100 py-3">Add New Category</button>
        <%end%>
    <%else%>
        <%=link_to new_category_transaction_path(params[:id]) do%>
            <button type="button" class="btn btn-outline-light w-100 py-3">Add New Transaction</button>
        <%end%>
    <%end%>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar p-1 d-flex justify-content-between align-items-center sticky-top text-light">
     <%case right_el%>
        <%when "menu"%>
            <button class="btn text-light" type="button" data-bs-toggle="offcanvas" data-bs-target="#staticBackdrop" aria-controls="staticBackdrop">
                <h3><i class="bi bi-list"></i></h3>
            </button>
        <%when "back"%>
            <h1>
              <%case title%>
                <%when "DETAILS"%>
                    <%=link_to "/" do%>
                      <i class="bi bi-arrow-left-short text-light"></i>
                    <%end%>
                <%when "New Transaction"%>
                    <%=link_to category_path(params[:category_id]) do%>
                      <i class="bi bi-arrow-left-short text-light"></i>
                    <%end%>
                <%when "New Category"%>
                    <%=link_to categorys_path do%>
                      <i class="bi bi-arrow-left-short text-light"></i>
                    <%end%>
                <%when "LOGIN", "REGISTER"%>
                    <%=link_to auth_path do%>
                      <i class="bi bi-arrow-left-short text-light"></i>
                    <%end%>
                <%when "Forgot Password"%>
                    <%=link_to "/users/sign_in" do%>
                      <i class="bi bi-arrow-left-short text-light"></i>
                    <%end%>
              <%end%>
            </h1>
     <%end%>
    <h1>
        <%= title%>
    </h1>
     <%case left_el%>
        <%when "search"%>
            <h3>
                <i class="bi bi-search"></i>
            </h3>
        <%when "Log in"%>
            Log in
        <%when "Next"%>
            Next
        <%when "none"%>
            <span class="none">none</span>
     <%end%>
</nav>

<%if @current_user.present?%>
  <div class="offcanvas offcanvas-start" data-bs-backdrop="static" tabindex="-1" id="staticBackdrop" aria-labelledby="staticBackdropLabel">
    <div class="offcanvas-header">
      <h5 class="offcanvas-title" id="staticBackdropLabel">Profile</h5>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="user-avatar m-auto d-flex justify-content-center align-items-center">
        <img src="https://robohash.org/rerumetqui.png?size=300x300&set=set1">
      </div>

      <h3 class="sidebar-user-name text-center mt-3"><%=@current_user.name%></h3>
      <div class="text-center mt-5">
         <%= button_to 'Logout', destroy_user_session_path, class: 'btn btn-danger m-auto', method: :delete %>
      </div>
    </div>
  </div>
<%end%>

app/views/transactions/new.html.erb
<%=render "shared/navbar", right_el: "back", left_el: "none", title: "New Transaction"%>
<%= form_with url: category_transactions_path(params[:category_id]), method: :post, local: true, scope: :transaction, class:"p-3" do |f|%>
    <div class="mb-3">
        <%= f.label :name, "Name", class:"form-label" %><br>
        <%= f.text_field :name,  :required => true, class:"form-control", placeholder: "Enter the name of the transaction" %>
    </div>
    <div class="mb-3">
        <%= f.label :amount, "Amount", class:"form-label" %><br>
        <%= f.number_field :amount,  :required => true, class:"form-control", placeholder: "How much did the transaction cost" %>
    </div>

    <p class="choose-categories-title">Choose categories</p>
    <em class="choose-categories-note"><%=@category.name%> is by default selected</em>
    <div class="mb-3 category-selects">
        <%= render "transactions/shared/select_form", categories: current_user.categorys%>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
<%end%>

app/views/transactions/shared/_select_form.html.erb
<%categories.each do |category|%>
    <div class="form-check">
        <input name="categorys[]"" class="form-check-input" type="checkbox"  <%="checked disabled" if category.id.to_s == params[:category_id]%> id="flexCheckChecked" value=<%=category.id%>>
        <label class="form-check-label" for="flexCheckChecked">
            <%=category.name%>
        </label>
    </div>
<%end%>

app/views/transactions/shared/_transaction.html.erb
<li class="transaction-item mb-2">
    <h3><%=transaction.name%>: <span class="transaction-price">$<%=transaction.amount%></span></h3>
    <em>
        <i class="bi bi-calendar"></i>
        13 Apr 2014 at 3:00 pm
    </em>
</li>